In [3]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn import tree

In [4]:
df=pd.read_csv('salaries.csv')

In [5]:
df.head()

  company                  job     degree  salary_more_than_100k
0  google      sales executive  bachelors                      0
1  google      sales executive    masters                      0
2  google     business manager  bachelors                      1
3  google     business manager    masters                      1
4  google  computer programmer  bachelors                      0

In [6]:
le_c = LabelEncoder()
le_j = LabelEncoder()
le_d = LabelEncoder()

In [7]:
input = df.drop('salary_more_than_100k',axis='columns')

In [8]:
target = df['salary_more_than_100k']

In [11]:
input['company_new']=le_c.fit_transform(input['company'])
input['job_new']=le_c.fit_transform(input['job'])
input['degree_new']=le_c.fit_transform(input['degree'])

In [12]:
input

,company,job,degree,company_new,job_new,degree_new
0,google,sales executive,bachelors,2,2,0
1,google,sales executive,masters,2,2,1
2,google,business manager,bachelors,2,0,0
3,google,business manager,masters,2,0,1
4,google,computer programmer,bachelors,2,1,0
5,google,computer programmer,masters,2,1,1
6,abc pharma,sales executive,masters,0,2,1
7,abc pharma,computer programmer,bachelors,0,1,0
8,abc pharma,business manager,bachelors,0,0,0
9,abc pharma,business manager,masters,0,0,1
10,facebook,sales executive,bachelors,1,2,0
11,facebook,sales executive,masters,1,2,1
12,facebook,business manager,bachelors,1,0,0
13,facebook,business manager,masters,1,0,1
14,facebook,computer programmer,bachelors,1,1,0
15,facebook,computer programmer,masters,1,1,1

In [17]:
input=input.drop(['degree','job','company'],axis='columns')

In [18]:
input

    company_new  job_new  degree_new
0             2        2           0
1             2        2           1
2             2        0           0
3             2        0           1
4             2        1           0
5             2        1           1
6             0        2           1
7             0        1           0
8             0        0           0
9             0        0           1
10            1        2           0
11            1        2           1
12            1        0           0
13            1        0           1
14            1        1           0
15            1        1           1

In [15]:
target

0     0
1     0
2     1
3     1
4     0
5     1
6     0
7     0
8     0
9     1
10    1
11    1
12    1
13    1
14    1
15    1
Name: salary_more_than_100k, dtype: int64

In [19]:
model=tree.DecisionTreeClassifier()
model.fit(input,target)

DecisionTreeClassifier()

In [22]:
model.score(input,target)

1.0

Is salary of Google, Computer Programmer, Bachelors degree > 100 k ?

In [23]:
model.predict([[2,1,0]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

array([0])

Is salary of Google, Computer Engineer, Masters degree > 100 k ?

In [24]:
model.predict([[2,1,1]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

array([1])

Thus the given data has been classified using Decision Tree and the model is created